import { WorkPackageDetail } from "@/components/site/WorkPackageDetail";
import { workPackageDetails } from "@/data/site";

export default function WP2Page() {
  const wp = workPackageDetails.find((item) => item.slug === "wp2");
  if (!wp) return null;

  return (
    <WorkPackageDetail
      title={wp.title}
      shortTitle={wp.shortTitle}
      summary={wp.summary}
      overview={wp.overview}
      focusAreas={wp.focusAreas}
      image={wp.image}
      methodologyTitle={wp.methodologyTitle}
workItems={[
  {
    title: "Probabilistic Multi-Target Search under Uncertainty",
    description:
      "A reinforcement learning framework that enables UAVs to efficiently search for multiple survivors in cluttered disaster environments under partial observability. The approach integrates probabilistic sensing confidence to guide navigation decisions when target locations are unknown, allowing the UAV to progressively refine its search strategy and improve localization performance in complex indoor scenarios.",
    imageSrc: "/images/wp2/icc2025-framework.jpg",
  },

  {
    title: "Adaptive Navigation in Changing Disaster Environments",
    description:
      "A hybrid learning framework designed to maintain reliable UAV navigation performance in evolving disaster environments. A diverse set of policies is trained offline to capture different structural conditions, while an online selection mechanism dynamically chooses the most suitable policy during deployment. This enables continuous adaptation to environmental changes such as debris movement or structural damage without requiring retraining.",
    imageSrc: "/images/wp2/kbs2026-framework.jpg",
  },

  {
    title: "Policy Library and Online Selection Mechanism",
    description:
      "A structured policy library is created during offline training, where each policy represents navigation behavior adapted to different environment layouts. During deployment, an online learning component continuously evaluates the environment and selects the most suitable policy in real time, allowing the UAV to respond effectively to changing obstacle configurations and target movement patterns.",
    imageSrc: "/images/wp2/kbs2026-policy-selection.png",
  },

  {
    title: "Sensor-Reactive Target Localization",
    description:
      "A sensing-driven navigation strategy that allows UAVs to follow aggregated signal patterns generated by multiple targets in damaged buildings. By directly leveraging sensor feedback rather than relying on prior maps or fixed target positions, the framework improves robustness in partially observable environments and supports efficient localization of trapped survivors in disaster scenarios.",
    imageSrc: "/images/wp2/sensor-reactive-search.png",
  },
]}
      futureWorkTitle="Future Work"
futureWorkText="Future work focuses on improving adaptation to unseen disaster environments using online learning and scene-aware decision making. The framework will be extended to operate on more realistic sensing data and complex building structures, enabling more reliable navigation and target localization under real-world uncertainty and dynamic conditions."
    />
  );
}